services:
  - type: web
    name: ice-reign-machine
    runtime: python
    buildCommand: ./build.sh
    startCommand: python main.py
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SOL_MAIN
        sync: false

